#!/bin/bash
### BEGIN INIT INFO
# Provides:          newnius
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: remote control
# Description:       remote control
### END INIT INFO

case "$1" in
	start)
		/usr/local/frp/frpc -c /usr/local/frp/frpc.ini
		;;
	stop)
		;;
esac

exit 0
