# https://github.com/hellowingy/wingy-announcement/blob/master/CONFIG.md
# https://github.com/waitusz/Rules-store/blob/master/Wingy/Wingy.conf
version: 2
adapter:
  - id: ss
    type: ss
    method: ss_method
    host: ss_host
    port: ss_port
    password: ss_pwd
  - id: speed
    type: speed
    adapters:
      - id: direct
        delay: 0
      - id: ss
        delay: 300
  - id: reject
    type: reject
    delay: 200
rule:
  # white list
  - type: list
    adapter: speed
    criteria:
      - s,tieba.baidu.com
      - s,imgsa.baidu.com
  # ads & tracking
  - type: list
    adapter: reject
    criteria:
      # Baidu
      - s,baidu.com
      - s,a.baidu.com
      - s,adm.baidu.com
      - s,als.baidu.com
      - s,api.m.baidu.com
      - s,api.youqian.baidu.com
      - s,baichuan.baidu.com
      - s,baidustatic.com
      - s,bce.baidu.com
      - s,bj.bcebos.com
      - s,c.baidu.com
      - s,cbjs.baidu.com
      - s,cbjslog.baidu.com
      - s,cpro.baidu.com
      - s,cpro.baidu.com.cn
      - s,cpro.baidustatic.com
      - s,cpro.zhidao.baidu.com
      - s,cpro2.baidu.com
      - s,crs.baidu.com
      - s,datax.baidu.com
      - s,dj1.baidu.com
      - s,drmcmm.baidu.com
      - s,dup.baidustatic.com
      - s,dxp.baidu.com
      - s,e.baidu.com
      - s,eclick.baidu.com
      - s,eiv.baidu.com
      - s,entry.baidu.com
      - s,gsp0.baidu.com
      - s,hc.baidu.com
      - s,hm.baidu.com
      - s,hm.baidu.com.cn
      - s,hmma.baidu.com
      - s,imageplus.baidu.com
      - s,mobads-logs.baidu.com
      - s,mobads.baidu.com
      - s,mtj.baidu.com
      - s,nsclick.baidu.com
      - s,pos.baidu.com
      - s,pups.baidu.com
      - s,pups.bdimg.com
      - s,push.zhanzhang.baidu.com
      - s,rp.baidu.com
      - s,sp1.baidu.com
      - s,spcode.baidu.com
      - s,static.tieba.baidu.com
      - s,su.bdimg.com
      - s,tongji.baidu.com
      - s,ubmcmm.baidustatic.com
      - s,ucstat.baidu.com
      - s,union.baidu.com
      - s,znsv.baidu.com
      - s,zz.bdstatic.com
      # Ali
      - s,adash.m.taobao.com
      - s,adashbc.m.taobao.com
      - s,adashx.m.taobao.com
      - s,adsh.m.taobao.com
      - s,afp.alicdn.com
      - s,afpmm.alicdn.com
      - s,alimama.cn
      - s,alimama.com
      - s,amdc.m.taobao.com
      - s,atanx.alicdn.com
      - s,atanx2.alicdn.com
      - s,gma.alicdn.com
      - s,hydra.alibaba.com
      - s,manager.channel.aliyun.com
      - s,sdkinit.taobao.com
      - s,show.re.taobao.com
      - s,simaba.taobao.com
      - s,simba.m.taobao.com
      - s,strip.taobaocdn.com
      - s,tanx.com
      # JD
      - s,bdsp.x.jd.com
      - s,policy.jd.cm
      - s,policy.jd.com
      - s,im-x.jd.com
      - s,jzt.jd.com
      - s,kepler.jd.com
      - s,keplerapi.jd.com
      - s,stat.m.jd.com
      - s,x.jd.com
      # Tencent
      - s,adsfile.qq.com
      - s,beacon.qq.com
      - s,boss.qzone.qq.com
      - s,btrace.qq.com
      - s,bugly.qq.com
      - s,c.l.qq.com
      - s,gdt.qq.com
      - s,ios.bugly.qq.com
      - s,livep.l.qq.com
      - s,lives.l.qq.com
      - s,livew.l.qq.com
      - s,mcgi.v.qq.com
      - s,monitor.uu.qq.com
      - s,news.l.qq.com
      - s,p.l.qq.com
      - s,pingjs.qq.com
      - s,pingma.qq.com
      - s,pingtcss.qq.com
      - s,report.qq.com
      - s,sdk.e.qq.com
      - s,t.l.qq.com
      - s,tajs.qq.com
      - s,tcss.qq.com
      - s,u.l.qq.com
      - s,uu.qq.com
      # Google
      - s,doubleclick.net
      - s,google-analytics.com
      - s,googleadservices.com
      - s,googleadsserving.cn
      - s,googlesyndication.com
      - s,googletagmanager.com
      - s,googletagservices.com
      # Twitter
      # Facebook
      # Others
      - s,00oo00.com
      - s,0311zs.net
      - s,0563d.com
      - s,13328888882.com
      - s,1571537.com
      - s,168.it168.com
      - s,168kk.com
      - s,19950501.com
      - s,2-80.cn
      - s,37cs.com
      - s,3apf.com
      - s,50bang.org
      - s,51.la
      - s,51ads.com
      - s,51vipedu.com
      - s,51yes.com
      - s,5207470.com
      - s,5334.com
      - s,56.itc.cn
      - s,58wanwan.net
      - s,5iwp.top
      - s,5leji.com
      - s,5lyq.com
      - s,5style.net
      - s,5y9nfpes.52pk.com
      - s,6604.org
      - s,6dad.com
      - s,70e.com
      - s,720in.com
      - s,778669.com
      - s,7pulxu.z0.glb.cloudcdn.com
      - s,801.tianya.cn
      - s,8556.com
      - s,88lmimg.com
      - s,95105012.com
      - s,990km.com
      - s,9cp.cn
      - s,9v.cn
      - s,aac-dmp.cn
      - s,acs86.com
      - s,ad-brix.com
      - s,ad-mapps.com
      - s,ad-plus.cn
      - s,ad-stir.com
      - s,ad-survey.com
      - s,ad.api.3g.tudou.com
      - s,ad.api.3g.youku.com
      - s,ad.qingting.fm
      - s,ad.sina.com.cn
      - s,ad.thsi.cn
      - s,ad.unimhk.com
      - s,ad.xiaomi.com
      - s,ad.ximalaya.com
      - s,ad2you.com
      - s,adcdn.goo.ne.jp
      - s,adcdn.hatena.ne.jp
      - s,adchina.com
      - s,adcolony.com
      - s,adcome.cn
      - s,adcontrol.tudou.com
      - s,adeventtracker.spotify.com
      - s,adgeo.163.com
      - s,adhouyi.com
      - s,adinall.com
      - s,adinfuse.com
      - s,adjust.com
      - s,adm.10jqka.com.cn
      - s,adm.72zx.com
      - s,adm.dxpmedia.com
      - s,adm.leju.sina.com.cn
      - s,admartzone.com
      - s,admaster.com.cn
      - s,admaster.mobi
      - s,admgr.qingting.fm
      - s,admob.com
      - s,admx.baixing.com
      - s,adnetworkperformance.com
      - s,adnxs.com
      - s,adofthyear.com
      - s,adplay.tudou.com
      - s,adpro.cn
      - s,ads-fa.cdn.spotify.com
      - s,ads.mobclix.com
      - s,ads.service.kugou.com
      - s,adsage.cn
      - s,adsage.com
      - s,adsame.com
      - s,adse.ximalaya.com
      - s,adsmogo.org
      - s,adspod.cn
      - s,adsymptotic.com
      - s,adtg.widerplanet.com
      - s,adultfriendfinder.com
      - s,aduu.cn
      - s,advertising.com
      - s,adview.cn
      - s,adwhirl.com
      - s,adwo.com
      - s,adxchina.cn
      - s,adxmi.com
      - s,adyun.com
      - s,adzerk.net
      - s,afp.qiyi.com
      - s,agkn.com
      - s,agn.aty.sohu.com
      - s,agrantsem.com
      - s,ai0.pub.funshion.com
      - s,aidata.io
      - s,aiwuqi.com.cn
      - s,akamaiedge.net
      - s,all.rising.com.cn
      - s,allyes.com
      - s,alog.umeng.co
      - s,alog.umeng.com
      - s,amung.us
      - s,analytics-union.xunlei.com
      - s,analytics.126.net
      - s,analytics.163.com
      - s,analytics.techweb.com.cn
      - s,anquan.org
      - s,ap.spotify.com
      - s,api.amplitude.com
      - s,api.biligame.com
      - s,api.cupid.iqiyi.com
      - s,api.iapps.ifeng.com
      - s,api.newad.ifeng.com
      - s,apk.shouji.koowo.com
      - s,appads.com
      - s,appcoachs.net
      - s,appintop.com
      - s,applifier.com
      - s,applovin.com
      - s,apppv.zol.com.cn
      - s,appsdt.com
      - s,appsflyer.com
      - s,appstat.dfcfw.com
      - s,ark.letv.com
      - s,atm.sina.com
      - s,atm.youku.com
      - s,au.umeng.com
      - s,avazutracking.net
      - s,baidu9635.com
      - s,baifendian.com
      - s,bam.nr-data.net
      - s,baoyatu.cc
      - s,bbs2.chinaz.com
      - s,bbsanalytics.weiphone.net
      - s,bccyyc.com
      - s,bdcpro.techweb.com.cn
      - s,bdimg.cnkang.com
      - s,bdj.tianya.cn
      - s,bdjiaoben.wmxa.cn
      - s,bduserlog.eastmoney.com
      - s,beacon.sina.com.cn
      - s,bestvogue.com
      - s,bfdcdn.com
      - s,biddingos.com
      - s,biddingx.com
      - s,bluekai.com
      - s,bobo.163.com
      - s,brand.sogou.com
      - s,bricknet.com
      - s,bs.da.hunantv.com
      - s,bxb.oupeng.com
      - s,bytedance.com
      - s,c.ns8d.com
      - s,c.youdao.com
      - s,c5.72zx.com
      - s,capp.simsimi.com
      - s,cast.ra.icast.cn
      - s,cc.xtgreat.com
      - s,ccs.ucweb.com
      - s,ccxhd.net
      - s,cdjyk.net
      - s,cdn.zampdsp.com
      - s,chartboost.com
      - s,chinassp.cn
      - s,cjlaoshi.com
      - s,ckm.iqiyi.com
      - s,cl.webterren.com
      - s,cl3.webterren.com
      - s,click.tianyaui.com
      - s,cmcm.com
      - s,cmcore.com
      - s,cms.laifeng.com
      - s,cn.wifi.com
      - s,cnzz.com
      - s,cnzz.net
      - s,cocounion.com
      - s,collect.tianya.cn
      - s,colorfulapp.com
      - s,comic.52pk.com
      - s,comic.hanhande.com
      - s,confirmation.gameloft.com
      - s,coolaiy.com
      - s,coolnay.com
      - s,coremetrics.com
      - s,counter.kingsoft.com
      - s,counter.yesky.com
      - s,cpc.brand.sogou.com
      - s,cpro.cr173.com
      - s,cpro.qqtn.com
      - s,cps.laifeng.com
      - s,cpx.to
      - s,cre.dp.sina.cn
      - s,crwdcntrl.net
      - s,csbew.com
      - s,ctsywy.com
      - s,cupid.iqiyi.com
      - s,cywl5.com
      - s,d.kugou.com
      - s,d0.sina.com.cn
      - s,d1.sina.com.cn
      - s,d31qbv1cthcecs.cloudfront.net
      - s,d3rt1990lpmkn.cloudfront.com
      - s,d7.sina.com.cn
      - s,dap.gentags.net
      - s,data.video.qiyi.com
      - s,data.vod.itc.cn
      - s,dc.letv.com
      - s,dcads.sina.com.cn
      - s,dcps.nuomi.com
      - s,dd.wenwo.com
      - s,de.as.pptv.com
      - s,deaohudong.com
      - s,dev.dc.letv.com
      - s,dm.toutiao.com
      - s,dmp.org.cn
      - s,dmp.sina.cn
      - s,dnspro.cn
      - s,dol.tianya.cn
      - s,domob.cn
      - s,domob.com.cn
      - s,domob.org
      - s,domobcdn.com
      - s,dongsi107.cn
      - s,dragonparking.com
      - s,dsp-impr2.youdao.com
      - s,dsp.fout.jp
      - s,dsp.youdao.com
      - s,dtscout.com
      - s,duomeng.cn
      - s,duomeng.net
      - s,duomeng.org
      - s,dxpmedia.com
      - s,easemob.com
      - s,eclicks.cn
      - s,economy.gmw.cn
      - s,eff.inte.sogou.com
      - s,egouz.com
      - s,ekeide.com
      - s,en.leturich.org
      - s,endsp.net
      - s,erebor.doban.com
      - s,exelator.com
      - s,exoclick.com
      - s,exp.3g.ifeng.com
      - s,eyeota.net
      - s,fastapi.net
      - s,fastlylb.net
      - s,feih.com.cn
      - s,fengbuy.com
      - s,file.market.xiaomi.com
      - s,file.ws.126.net
      - s,files.adform.net
      - s,findjapan.cn
      - s,flurry.com
      - s,forjs.net
      - s,fsf.org
      - s,fugetech.com
      - s,fz.letv.com
      - s,g.q4ik.com
      - s,g.tbcdn.cn
      - s,g1.163.com
      - s,g3.letv.com
      - s,gad.kugpu.com
      - s,game.ifeng.com
      - s,game.kuwo.cn
      - s,gcapi.sy.kugou.com
      - s,gclick.cn
      - s,gg.kogou.com
      - s,ggdoubi.com
      - s,ggfeng.com
      - s,ggjia.cn
      - s,good.ta80.com
      - s,googeadsserving.cn
      - s,gorgon.youdao.com
      - s,goto.sms.sohu.com
      - s,gouzb.com
      - s,goyoo.cn
      - s,goyoo.com.cn
      - s,goyoogroup.cn
      - s,gs.mydown.yesky.com
      - s,gslb.spotify.com
      - s,gtags.net
      - s,guanggaojia.cn
      - s,guomob.com
      - s,gw5.push.mcp.weibo.cn
      - s,h04.hxsame.hexun.com
      - s,h5channel.51pgzs.com
      - s,hainan.net
      - s,haitaoad.nosdn.127.net
      - s,haiyunx.com
      - s,haowj.com.cn
      - s,heads-ecb.spotify.com
      - s,huimee.net
      - s,hwcdn.net
      - s,hxsame.hexun.com
      - s,i.go.sohu.com
      - s,i8.com.cn
      - s,i8ad.cn
      - s,i8app.cn
      - s,i8card.com
      - s,i8cn.com
      - s,i8desk.com
      - s,i8os.cn
      - s,ibianli.com.cn
      - s,ibsnssdk.com
      - s,icafe8.cn
      - s,icast.cn
      - s,ichannel.snssdk.com
      - s,idougou.cn
      - s,idougou.com
      - s,idougou.com.cn
      - s,ifashion.ifeng.com
      - s,iis3g.deliver.ifeng.com
      - s,img.fd7c.com
      - s,img.il8r.com
      - s,img.twcczhu.com
      - s,img.ujian.cc
      - s,immob.cn
      - s,imochy.com
      - s,impact.applifier.com
      - s,impservice.union.youdao.com
      - s,impservice2.youdao.com
      - s,index8.cn
      - s,ingameads.gameloft.com
      - s,inmobi.com
      - s,inmobicdn.net
      - s,inmobisdk-a.akamaihd.net
      - s,inte.sogou.com
      - s,intely.cn
      - s,ip000.cn
      - s,ipcheck1.39.net
      - s,ipduo.cn
      - s,ipengtai.huanqiu.com
      - s,ipinyou.com
      - s,irs01.com
      - s,itv.hexun.com
      - s,iuyhjn.com
      - s,iwencai.com
      - s,iwstat.tudou.com
      - s,j.pcpop.com
      - s,j.qiqiyii.com
      - s,jfcdns.com
      - s,jiaadx.com
      - s,jiafe.com
      - s,jiaoben.eastday.com
      - s,jiaoyueba.com
      - s,jisucn.com
      - s,jixing8.com
      - s,joyslink.com
      - s,js-agent.newrelic.com
      - s,js.revsci.net
      - s,juejdkio.com
      - s,juicyads.com
      - s,jump.luna.58.com
      - s,jusha.com
      - s,jxwcbf.com
      - s,jzv1.com
      - s,kdatacenter.com
      - s,kejet.net
      - s,keyrun.cn
      - s,keytui.com
      - s,ksyun.com
      - s,ktplay.cn
      - s,kuangtech.com
      - s,kukuplay.com
      - s,kxbeta.com
      - s,kxwan.com
      - s,latrobe.edu.au
      - s,lewifi.cn
      - s,lianmeng.360.cn
      - s,link0.com
      - s,linkpage.cn
      - s,linkvans.com
      - s,ljrtb.cn
      - s,lnk0.com
      - s,localytics.com
      - s,log.da.hunantv.com
      - s,log.kuwo.cn
      - s,log.mix.sina.com.cn
      - s,log.snssdk.com
      - s,log.stat.kugou.com
      - s,log.v2.hunantv.com
      - s,logger.qingting.fm
      - s,love.bobo.com
      - s,lstat.youku.com
      - s,lzplugin.bshare.cn
      - s,m.aty.sohu.com
      - s,m.sa.sm.cn
      - s,madgic.mobi
      - s,madmini.com
      - s,majorserving.com
      - s,map.dxpmedia.com
      - s,market.spotify.com
      - s,market.xiaomi.com
      - s,markmonitor.com
      - s,mathtag.com
      - s,mb.hd.sohu.com.cn
      - s,mct01.com
      - s,media.tianjimedia.com
      - s,media.yesky.com
      - s,media8.cn
      - s,mediasmart.es
      - s,mediav.com
      - s,mega.mlt01.com
      - s,mengmob.com
      - s,meta.video.qiyi.com
      - s,miaoz.com.cn
      - s,miaozhen.com
      - s,minisite.letv.com
      - s,minisplat.cn
      - s,mixpanel.com
      - s,mmg.aty.sohu.com
      - s,mmstat.com
      - s,mob.com
      - s,mobaders.com
      - s,mobileapi.speedtest.net
      - s,mobpro.cn
      - s,moogos.com
      - s,mookie1.com
      - s,mopub.com
      - s,mp4.res.hunantv.com
      - s,msg.71.am
      - s,mtab.clickmon.co.kr
      - s,mvads.kugou.com
      - s,mydas.mobi
      - s,myhard.com
      - s,n.mark.letv.com
      - s,nexac.com
      - s,niuxgame77.com
      - s,nstat.tudou.com
      - s,oc.umeng.com
      - s,oimageb4.ydstatic.com
      - s,oimageb5.ydstatic.com
      - s,onetad.com
      - s,optaim.com
      - s,optimix.asia
      - s,optimix.cn
      - s,otherlevels.com
      - s,p-log.ykimg.com
      - s,p.inte.sogou.com
      - s,p.l.ykimg.com
      - s,p0y.cn
      - s,p2.hunantv.com
      - s,pailady.com
      - s,paopao.iqiyi.com
      - s,partner.toutiao.com
      - s,pcookie.mlt01.com
      - s,pd.brand.sogou.com
      - s,pgdt.gtimg.cn
      - s,pippio.com
      - s,pixel.wp.com
      - s,playnimei.cn
      - s,plog.dc.letv.com
      - s,po.funshion.com
      - s,pop6.com
      - s,pro.cn
      - s,pro.hoye.letv.com
      - s,pro.letv.com
      - s,profile.ams50.cloudfront.net
      - s,pubnative.net
      - s,punchbox.org
      - s,pushwoosh.com
      - s,pv.alert.autohome.com.cn
      - s,pv.funshion.com
      - s,px.3.cn
      - s,qf.56.com
      - s,qos.117go.com
      - s,qqabcd8899.cn
      - s,qtmojo.com
      - s,quote.tool.hexun.com
      - s,r.yy.com
      - s,ra.icast.cn
      - s,rd.da.netease.com
      - s,rhocdn.net
      - s,rlcdn.com
      - s,rollout.io
      - s,rtax.criteo.com
      - s,rtmonitor.kugou.com
      - s,run.wmxa.cn
      - s,rwq.youle55.com
      - s,s.cr-nielsen.com
      - s,s.go.sohu.com
      - s,sax.sina.cn
      - s,sax.sina.com.cn
      - s,score.my.tv.sohu.com
      - s,scorecardresearch.com
      - s,sdkapp.mobile.sina.cn
      - s,secure-ds.serving-sys.com
      - s,serving-sys.com
      - s,shared.youdao.com
      - s,show.58dtpf.com
      - s,show.pipi7788.com
      - s,show.xiazai8844.net
      - s,shunwang.cn
      - s,sijiys.com
      - s,simpli.if
      - s,skeettools.com
      - s,slog.sina.cn
      - s,smartadserver.com
      - s,so.hexun.com
      - s,sohu.wrating.com
      - s,souluo.net
      - s,sp.qf.56.com
      - s,ssacdn.com
      - s,ssl-static.baifendian.com
      - s,ssp-ces.gameloft.com
      - s,st.vq.ku6.cn
      - s,stat.10jqka.com.cn
      - s,stat.adirects.com
      - s,stat.funshion.net
      - s,stat.it168.com
      - s,stat.letv.com
      - s,stat.tudou.com
      - s,stat.youku.com
      - s,static.applifier.com
      - s,static.bshare.cn
      - s,static1.bfdcdn.com
      - s,statics.motu.pagechoice.net
      - s,stats.tudou.com
      - s,supersonicads-a.akamaihd.net
      - s,supersonicads.com
      - s,szhk.com
      - s,tailorforme.com
      - s,talkingdata.net
      - s,tapjoyads.com
      - s,telemetryverification.net
      - s,testm.10jqka.com.cn
      - s,tg.1155t.cn
      - s,thescenseproject.com
      - s,tiqcdn.com
      - s,tjs.sjs.sinajs.cn
      - s,tongji.linezing.com
      - s,tongji.techweb.com.cn
      - s,track.ra.icast.cn
      - s,ttwgou.com
      - s,tui1999.com
      - s,tutuapp.com
      - s,txt789.com
      - s,tynt.com
      - s,u1.img.mobile.sina.cn
      - s,umapi.cn
      - s,umeng.co
      - s,umeng.com
      - s,umeng.net
      - s,umengcloud.com
      - s,umsns.com
      - s,umtrack.com
      - s,union.xunlei.com
      - s,union.youdao.com
      - s,unity3d.com
      - s,update.mobile.kugou.com
      - s,ushaqi.com
      - s,utrack.hexun.com
      - s,uyunad.com
      - s,v1.ujian.cc
      - s,v2.log.hunantv.com
      - s,v2html.atm.youku.com
      - s,valf.atm.youku.com
      - s,vamaker.com
      - s,venus.alfhaily.me
      - s,vgdtimg.cn
      - s,videojj.com
      - s,vip.yule8.net
      - s,vipp.rwjfs.com
      - s,voiceads.cn
      - s,vtac.cn
      - s,vungle.cn
      - s,w8.com.cn
      - s,wan.liebao.cn
      - s,wan.sogou.com
      - s,waps.cn
      - s,we.tm
      - s,webstat.kuwo.cn
      - s,webterren.com
      - s,whxhxwz.com
      - s,wifi6.cn
      - s,wifiapi01.51y5.net
      - s,wifiapi02.51y5.net
      - s,wiyun.com
      - s,wkanx.com
      - s,wmdeal.qtmojo.com
      - s,wooboo.com.cn
      - s,wqmobile.com
      - s,wrating.com
      - s,wt.39.net
      - s,wuxian.fd.zol-img.com.cn
      - s,x.da.hunantv.com
      - s,xiaoyun.com
      - s,xiaoyunwifi.cn
      - s,xihuan8.cn
      - s,xihuanba.cn
      - s,xingjuhe.com
      - s,xiuxiu.mobile.meitudata.com
      - s,xiyou-g.com
      - s,xrtzf.com
      - s,xs.houyi.baofeng.net
      - s,xunio.com
      - s,y0game.com
      - s,ychun03.com
      - s,yes1.feng.com
      - s,yhdichan.com
      - s,yieldmo.com
      - s,youmi.net
      - s,youzu.com
      - s,yoyi.com.cn
      - s,yoyi.tv
      - s,yunpro.cn
      - s,zdbb.net
      - s,zdw.w8.com.cn
      - s,zhaochina.com
      - s,zhiziyun.com
      - s,zhongxinghuanyu.com
      - s,ziffdavis.com
      - s,zyiis.net
      - s,zzrcz.com
      - s.log.da.hunantv.com
      - s.log.v2.hunantv.com
  # intranet
  - type: iplist
    adapter: direct
    criteria:
      # IP-CIDR-Direct
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 169.254.0.0/16
      - 224.0.0.0/8
  - type: DNSFail
    adapter: ss
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: all
    adapter: speed
